// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	PersonID  pgtype.UUID        `db:"person_id" json:"person_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Body      *string            `db:"body" json:"body"`
}

type Person struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Username *string     `db:"username" json:"username"`
}
