// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CheckUser = `-- name: CheckUser :one
select id, username from persons
where id = $1
`

func (q *Queries) CheckUser(ctx context.Context, id pgtype.UUID) (*Person, error) {
	row := q.db.QueryRow(ctx, CheckUser, id)
	var i Person
	err := row.Scan(&i.ID, &i.Username)
	return &i, err
}

const CreateMessage = `-- name: CreateMessage :one
insert into messages(person_id, body)
VALUES ($1, $2)
returning id, person_id, created_at, body
`

type CreateMessageParams struct {
	PersonID pgtype.UUID `db:"person_id" json:"person_id"`
	Body     *string     `db:"body" json:"body"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (*Message, error) {
	row := q.db.QueryRow(ctx, CreateMessage, arg.PersonID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CreatedAt,
		&i.Body,
	)
	return &i, err
}

const CreateUser = `-- name: CreateUser :one
insert into persons(username) VALUES ($1)
returning id, username
`

func (q *Queries) CreateUser(ctx context.Context, username *string) (*Person, error) {
	row := q.db.QueryRow(ctx, CreateUser, username)
	var i Person
	err := row.Scan(&i.ID, &i.Username)
	return &i, err
}

const Messages = `-- name: Messages :many
select id, person_id, created_at, body from messages
limit $1 offset $2
`

type MessagesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) Messages(ctx context.Context, arg MessagesParams) ([]*Message, error) {
	rows, err := q.db.Query(ctx, Messages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.CreatedAt,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MessagesByPerson = `-- name: MessagesByPerson :many
select id, person_id, created_at, body
from messages
where person_id = $1
limit $2 offset $3
`

type MessagesByPersonParams struct {
	PersonID pgtype.UUID `db:"person_id" json:"person_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) MessagesByPerson(ctx context.Context, arg MessagesByPersonParams) ([]*Message, error) {
	rows, err := q.db.Query(ctx, MessagesByPerson, arg.PersonID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.CreatedAt,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const Users = `-- name: Users :many
select id, username from persons
limit $1 offset $2
`

type UsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) Users(ctx context.Context, arg UsersParams) ([]*Person, error) {
	rows, err := q.db.Query(ctx, Users, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
