// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckUser(ctx context.Context, id pgtype.UUID) (*Person, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (*Message, error)
	CreateUser(ctx context.Context, username *string) (*Person, error)
	Messages(ctx context.Context, arg MessagesParams) ([]*Message, error)
	MessagesByPerson(ctx context.Context, arg MessagesByPersonParams) ([]*Message, error)
	Users(ctx context.Context, arg UsersParams) ([]*Person, error)
}

var _ Querier = (*Queries)(nil)
